targets:
  $default:
    builders:
      drift_dev:
        options:
          override_hash_and_equals_in_result_sets: true
          generate_connect_constructor: true
          sql:
            dialect: sqlite
            options:
              version: "3.37"
              modules:
                - json1
                - fts5