name: example
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: simon <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  sally:
    path: ../sally

dev_dependencies:
  sally_generator:
    path: ../sally_generator
  build_runner:
  pedantic: ^1.0.0
  test: ^1.0.0
