language: dart

env:
  - PKG="sally"
  - PKG="sally_generator"

dart:
  - stable

matrix:
  include:
    - name: "Sally"
      env: PKG="sally"
    - name: "Sally generator"
      env: PGK="sally_generator"

script: ./tool/travis.sh dartfmt dartanalyzer test

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
