language: dart

# todo bring back stable. Seems like coverage hangs on 2.3.0
dart:
  - "2.2.0"
env:
  - PKG="moor"
  - PKG="moor_generator"

script: ./tool/mono_repo_wrapper.sh
after_success: ./tool/upload_coverage.sh

cache:
  directories:
    - "$HOME/.pub-cache"
