language: dart

dart:
  - stable

env:
  - PKG="sally"
  - PKG="sally_generator"

script: ./tool/mono_repo_wrapper.sh

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master

cache:
  directories:
    - "$HOME/.pub-cache"
    - sally/.dart_tool/build
    - sally_generator/.dart_tool/build
