language: dart

dart:
  - stable
env:
  - PKG="moor"
  - PKG="moor_generator"
  - PKG="sqlparser"

script: ./tool/mono_repo_wrapper.sh
after_success: ./tool/upload_coverage.sh

cache:
  directories:
    - "$HOME/.pub-cache"
