language: dart

dart:
  - stable

env:
  - PKG="moor"
  - PKG="moor_generator"

script: ./tool/mono_repo_wrapper.sh

# Only building master means that we don't run two builds for each pull request.
branches:
  only:
    - master
    - develop

cache:
  directories:
    - "$HOME/.pub-cache"
    - moor/.dart_tool/build
    - moor_generator/.dart_tool/build
