# We use netlify to deploy the documentation.

[build]
  base = "docs/"
  publish = "docs/public"
  command = 'git submodule update --init --recursive && HUGO_ENV="production" hugo'

[[redirects]]
  from = "https://moor.netlify.com/*"
  to = "https://moor.simonbinder.eu/:splat"
  status = 301
  force = true