# We use netlify to deploy the documentation.

[build]
  base = "docs"
  publish = "docs/public"
  command = 'git submodule update --init --recursive && npm -i && hugo'

[[redirects]]
  from = "https://moor.netlify.com/*"
  to = "https://moor.simonbinder.eu/:splat"
  status = 301
  force = true

[context.production]
  environment = { HUGO_ENV="production", HUGO_VERSION="0.74.3" }

[context.deploy-preview]
  environment = { HUGO_VERSION="0.74.3" }