# This pubspec file exists so that this repository can show up in the generated list of community
# repositories. It's not meant to serve as an actual pub file.

name: sally
description: Sally is a safe and reactive persistence library for Dart applications
homepage: https://github.com/simolus3/sally
authors:
  - Flutter Community <community@flutter.zone>
  - Simon Binder <simolus3@gmail.com>
maintainer: Simon Binder (@simolus3)

environment:
  sdk: '>=2.0.0 <3.0.0'
