name: analyzer_load_moor_plugin
version: 1.0.0
description: This pubspec is a part of moor and determines the version of the moor analyzer to load

dependencies:
  moor_generator: ^1.6.0

dependency_overrides:
  moor_generator:
    path: ../../../moor_generator