name: sqlparser
description: Parses sqlite statements and performs static analysis on them
version: 0.13.0-nullsafety.0
homepage: https://github.com/simolus3/moor/tree/develop/sqlparser
#homepage: https://moor.simonbinder.eu/
issue_tracker: https://github.com/simolus3/moor/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  meta: ^1.3.0-nullsafety
  collection: ^1.15.0-nullsafety.4
  source_span: ^1.8.0-nullsafety
  charcode: ^1.2.0-nullsafety

dev_dependencies:
  test: ^1.16.0-nullsafety
  path: ^1.8.0-nullsafety
  ffi: ^0.2.0-nullsafety
  sqlite3: ^0.1.9-nullsafety