name: moor
description: Moor is a safe and reactive persistence library for Dart applications
version: 4.0.0-nullsafety.0
repository: https://github.com/simolus3/moor
homepage: https://moor.simonbinder.eu/
issue_tracker: https://github.com/simolus3/moor/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  meta: ^1.3.0-nullsafety.6
  # We'd prefer convert ^3.0.0 for nullsafety, (we have a dependency_override) for that, but large chunks of the Dart
  # ecosystem don't support version 3.0.0 yet, so we support older versions for compatibility.
  convert: ">=2.1.1 <4.0.0"
  collection: ^1.15.0-nullsafety.5
  synchronized: ^3.0.0-nullsafety
  pedantic: ^1.10.0-nullsafety.3
  sqlite3: ^0.1.9-nullsafety

dev_dependencies:
  build_test: ^1.3.0
  build_runner_core: ^6.1.0
  moor_generator: ^3.2.0
  uuid: ^2.0.0
  path: ^1.6.4
  build_runner: '^1.10.4'
  test: ^1.16.0-nullsafety
  mockito: ^4.1.3
  rxdart: ^0.24.0 # used to test compatibility with stream queries

dependency_overrides:
  moor_generator:
    path: ../moor_generator
  sqlparser:
    path: ../sqlparser

  # Remove after https://github.com/dart-lang/mockito/issues/297 is fixed
  mockito:
    git:
      url: https://github.com/simolus3/mockito.git
      ref: version-for-moor

  uuid:
    git:
      url: https://github.com/Daegalus/dart-uuid.git
      ref: nullsafety

  crypto:
    git:
      url: https://github.com/dart-lang/crypto.git
      ref: master

  convert: ^3.0.0-nullsafety