name: moor
description: Moor is a safe and reactive persistence library for Dart applications
version: 3.5.0-dev
repository: https://github.com/simolus3/moor
homepage: https://moor.simonbinder.eu/
issue_tracker: https://github.com/simolus3/moor/issues

environment:
  sdk: '>=2.12.0-0 <3.0.0'

dependencies:
  meta: ^1.3.0-nullsafety.6
  convert: ^2.1.1
  collection: ^1.15.0-nullsafety.5
  synchronized: ^2.1.0
  pedantic: ^1.10.0-nullsafety.3
  sqlite3: ^0.1.9-nullsafety

dev_dependencies:
  analyzer: ^0.40.6
  moor_generator: ^3.2.0
  uuid: ^2.0.0
  path: ^1.6.4
  build_runner: '^1.10.4'
  test: ^1.16.0-nullsafety
  mockito: ^4.1.3
  rxdart: ^0.24.0 # used to test compatibility with stream queries

dependency_overrides:
  moor_generator:
    path: ../moor_generator
  sqlparser:
    path: ../sqlparser

  synchronized:
    git:
      url: https://github.com/tekartik/synchronized.dart.git
      ref: null_safety
      path: synchronized

  # Remove after https://github.com/dart-lang/mockito/issues/297 is fixed
  mockito:
    git:
      url: https://github.com/simolus3/mockito.git
      ref: generate-inheritance
