name: sally_flutter
description: Flutter implementation for the sally database
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  sally:
    path: ../sally
  sqflite: ^1.1.0
  path: ^1.6.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

