name: mysql
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Simon Binder <oss@simonbinder.eu>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  moor: ^1.6.0
  sqljocky5: ^2.2.0

dev_dependencies:
  test: ^1.6.0
  moor_generator: ^1.6.0
  build_runner:

dependency_overrides:
  moor:
    path: ../../moor