name: end_to_end_testing
description: A project to test sally.

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  sally:
    path: ../sally
  sqlite2: ^0.5.0
  path: ^1.4.1

dev_dependencies:
  sally_generator:
    path: ../sally_generator
  built_value_generator: ^6.3.0
  build_runner:
  build_test:
  test: ^1.0.0