name: manager
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.1 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  drift: ^2.16.0
  drift_dev: ^2.16.0
  flutter_riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  flutter_hooks: ^0.20.5
  riverpod_annotation: ^2.3.5
  sqlite3_flutter_libs: ^0.5.20
  sqlite3: ^2.4.2
  path: ^1.9.0
  path_provider: ^2.1.2
  flex_color_picker: ^3.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  riverpod_generator: ^2.4.0
  custom_lint: ^0.6.4
  riverpod_lint: ^2.3.10

flutter:
  uses-material-design: true

dependency_overrides:
  drift_dev:
    path: C:/Users/dicke/drift/drift_dev
  drift:
    path: C:/Users/dicke/drift/drift
