name: with_built_value
publish_to: none
version: 1.0.0

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  moor: ^3.2.0
  built_value: ^7.1.0

dev_dependencies:
  moor_generator: ^2.1.0
  built_value_generator: ^7.1.0
  build_runner: '^1.10.1'

dependency_overrides:
  moor:
    path: ../../moor
  moor_generator:
    path: ../../moor_generator
  sqlparser:
    path: ../../sqlparser

  # todo: Remove after built_value supports analyzer ^0.40
  analyzer: 0.40.4