name: with_built_value
publish_to: none
version: 1.0.0

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  moor: ^4.0.0
  built_value: ^8.0.0

dev_dependencies:
  moor_generator: ^4.0.0
  built_value_generator: ^8.0.0
  build_runner: ^1.11.1

dependency_overrides:
  moor:
    path: ../../moor
  moor_generator:
    path: ../../moor_generator
  sqlparser:
    path: ../../sqlparser

  # todo: Remove after we can use analyzer ^1.0.0
  analyzer: 0.40.4
  dart_style: '>=1.2.0 <1.3.0'
  convert: ^3.0.0-nullsafety