name: with_built_value
publish_to: none
version: 1.0.0

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  moor: ^4.0.0
  built_value: ^8.0.0

dev_dependencies:
  moor_generator: ^4.0.0
  built_value_generator: ^8.0.0
  build_runner: ^1.11.1

dependency_overrides:
  moor:
    path: ../../moor
  moor_generator:
    path: ../../moor_generator
  sqlparser:
    path: ../../sqlparser
  # todo: Remove as soon as built_value_generator supports the latest analyzer and build packages
  analyzer: ^1.0.0
  convert: ^3.0.0-nullsafety
  build: ^2.0.0
  source_gen: ^0.9.10+4
