name: with_built_value
publish_to: none
version: 1.0.0

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  moor: ^2.3.0
  moor_ffi: ^0.4.0
  built_value: ^7.0.0

dev_dependencies:
  moor_generator: ^2.1.0
  built_value_generator: ^7.0.0
  build_runner: '>=1.3.0 <2.0.0'

dependency_overrides:
  moor:
    path: ../../moor
  moor_ffi:
    path: ../../moor_ffi
  moor_generator:
    path: ../../moor_generator
  sqlparser:
    path: ../../sqlparser