name: sally_example
description: A todo list application that uses sally to store data

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  sally_flutter:
    path: ../

dev_dependencies:
  build_runner:
  sally_generator:
    path: ../../sally_generator
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
