name: web_worker_example
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js: ^0.6.3
  stream_channel: ^2.1.0
  moor:
  moor_generator:

dev_dependencies:
  build_runner: ^2.0.0
  build_web_compilers: ^3.0.0
  pedantic: ^1.9.0

dependency_overrides:
  drift:
    path: ../../drift
  moor:
    path: ../../moor
  moor_generator:
    path: ../../moor_generator
  sqlparser:
    path: ../../sqlparser
