name: sally
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Simon Binder <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: '>= 1.0.0 <2.0.0'

dev_dependencies:
  sally_generator:
    path: ../sally_generator
  build_runner: ^1.2.6
  build_test: ^0.10.6
  test: ^1.5.3
  mockito: ^4.0.0