name: sally
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com
# author: Simon Binder <email@example.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: '>= 1.0.0 <2.0.0'
  sqflite: ^1.1.0
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.0.0
