name: sally
description: Sally is a safe and reactive persistence library for Dart applications
version: 1.0.0
homepage: https://github.com/simolus3/sally
authors:
  - Flutter Community <community@flutter.zone>
  - Simon Binder <simolus3@gmail.com>
maintainer: Simon Binder (@simolus3)

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  meta: '>= 1.0.0 <2.0.0'

dev_dependencies:
  sally_generator:
    path: ../sally_generator
  build_runner: ^1.2.0
  build_test: ^0.10.6
  test: ^1.5.3
  mockito: ^4.0.0