name: encrypted_moor
description: Encryption support for moor, built with sqflite_sqlcipher
version: 1.0.0
author: Simon Binder <oss@simonbinder.eu>

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  moor: ^3.0.0
  sqflite_sqlcipher: ^1.0.0+6

dependency_overrides:
  moor:
    path: ../../moor
