builders:
  versions:
    import: 'tool/write_versions.dart'
    build_to: cache
    builder_factories: ["writeVersions"]
    build_extensions: {"$package$": ["lib/versions.json"]}

targets:
  prepare:
    builders:
      "|versions":
        enabled: true
      code_snippets:
        enabled: true
        generate_for:
          - "lib/snippets/**/*.dart"
          - "lib/snippets/*.dart"
    auto_apply_builders: false
    sources:
      - "$package$"
      - "lib/versions.json"
      - "lib/snippets/**"
      - "tool/write_versions.dart"

  $default:
    dependencies: [":prepare"]
    builders:
      built_site:
        release_options:
          environment: "preview"
      build_web_compilers|entrypoint:
        release_options:
          # Turn of null assertions for release builds, it looks like this
          # makes generated code slightly smaller.
          native_null_assertions: false
          dart2js_args:
            - "-O4"
            - "--csp"
      moor_generator:
        enabled: false
      code_snippets:
        enabled: false
    sources:
      - "lib/**"
      - "pages/**"
      - "templates/**"
      - "web/**"
      - "$package$"
      - "pubspec.yaml"
      - "theme.yaml"
      - "website.yaml"
