targets:
  $default:
    builders:
      built_site:
        release_options:
          environment: "preview"
      build_web_compilers|entrypoint:
        release_options:
          # Turn of null assertions for release builds, it looks like this
          # makes generated code slightly smaller.
          native_null_assertions: false
          dart2js_args:
            - "-O4"
            - "--csp"
    sources:
      - "lib/**"
      - "pages/**"
      - "templates/**"
      - "web/**"
      - "$package$"
      - "pubspec.yaml"
      - "theme.yaml"
      - "website.yaml"
