name: moor_ffi
description: "Experimental moor implementation that uses dart:ffi"
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.5.0-dev <2.6.0"

dependencies:
  moor: ^2.0.0
#  flutter:
#    sdk: flutter

dev_dependencies:
  test: ^1.6.0

flutter:
  plugin:
    # the flutter.plugin key needs to exists so that this project gets recognized as a plugin when imported. We need to
    # get recognized as a plugin so that our build scripts are executed.
    foo: bar

dependency_overrides:
  moor:
    path: ../moor