name: moor_ffi
description: "Provides sqlite bindings using dart:ffi, including a moor executor"
version: 0.8.0
homepage: https://github.com/simolus3/moor/tree/develop/moor_ffi
issue_tracker: https://github.com/simolus3/moor/issues

environment:
  sdk: ">=2.6.0 <3.0.0"
  flutter: any

dependencies:
  moor: ^3.0.0
  ffi: ^0.1.3
  collection: ^1.0.0
  meta: ^1.0.2
  # moor_ffi used to include sqlite on Flutter builds, so we depend on sqlite3_flutter_libs to continue this behavior.
  # This makes moor_ffi a Flutter-only package - not what we want, but now it's deprecated anyways. Non-Flutter users
  # should use the `sqlite3` package instead.
  sqlite3_flutter_libs: ^0.2.0

dev_dependencies:
  test: ^1.6.0
  path: ^1.6.0
