name: moor_ffi
description: "Provides sqlite bindings using dart:ffi, including a moor executor"
version: 0.7.0
homepage: https://github.com/simolus3/moor/tree/develop/moor_ffi
issue_tracker: https://github.com/simolus3/moor/issues

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  moor: ^3.0.0
  ffi: ^0.1.3
  collection: ^1.0.0
  meta: ^1.0.2

dev_dependencies:
  test: ^1.6.0
  path: ^1.6.0

#dependency_overrides:
#  moor:
#    path: ../moor

flutter:
  plugin:
    platforms:
      # At the moment, we only have a custom build script for Android. For that to be included, we have to provide a
      # plugin class (even though moor_ffi contains no platform-specific code). The plugin class is just an empty stub
      # here.
      android:
        pluginClass: MoorFfiPlugin
        package: eu.simonbinder.moor_ffi