name: vm
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: Simon Binder <oss@simonbinder.eu>

environment:
  sdk: '>=2.4.0 <3.0.0'

dependencies:
  moor_ffi:
    path: ../../../moor_ffi
  tests:
    path: ../tests

dev_dependencies:
  test: ^1.5.0
  # TODO: This is a temporary workaround, revert after https://github.com/dart-lang/sdk/issues/39702
  analyzer: '<0.39.2'

dependency_overrides:
  moor:
    path: ../../../moor
