name: moor_example
description: A todo list application that uses moor to store data

version: 1.0.0+1

environment:
  sdk: ">=2.0.0-dev.68.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  intl:
  cupertino_icons: ^0.1.2
  rxdart: 0.20.0
  moor_flutter:
    path: ../

dev_dependencies:
  build_runner:
  moor_generator:
    path: ../../moor_generator
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
